version: "3"

services:
  py-dev:
    build: ./services/py1
    command: sh -c "pip install -r requirements.txt && python -m server"
    environment:
      - PORT=9000
      - FLASK_ENV=development
    ports:
      - "9000:9000"
    working_dir: /root/py1
    volumes:
      - ./services/py1:/root/py1:cached # <--- This will map ./py1 to /root/py1 inside the container.
      - ./working:/root/py-dev
